import 'package:flutter/material.dart';

/// Activity icons: stored by key in the database, grouped for the picker and
/// searchable by Italian keywords. Keys from 1.0 are kept.
class ActivityIcon {
  const ActivityIcon(this.key, this.icon, this.words);
  final String key;
  final IconData icon;
  final String words;
}

const Map<String, List<ActivityIcon>> kIconGroups = {
  'Studio': [
    ActivityIcon('book', Icons.menu_book_rounded, 'libro studio leggere lettura'),
    ActivityIcon('school', Icons.school_rounded, 'scuola università laurea lezione'),
    ActivityIcon('stories', Icons.auto_stories_rounded, 'libro romanzo lettura storie'),
    ActivityIcon('notes', Icons.edit_note_rounded, 'appunti note scrivere'),
    ActivityIcon('science', Icons.science_rounded, 'scienza chimica laboratorio'),
    ActivityIcon('calc', Icons.calculate_rounded, 'matematica calcolo conti'),
    ActivityIcon('translate', Icons.translate_rounded, 'lingue inglese traduzione'),
    ActivityIcon('brain', Icons.psychology_rounded, 'mente cervello pensare psicologia'),
    ActivityIcon('idea', Icons.lightbulb_rounded, 'idea progetto pensiero'),
    ActivityIcon('library', Icons.library_books_rounded, 'biblioteca libri ripasso'),
    ActivityIcon('history', Icons.history_edu_rounded, 'storia tesi scrittura'),
    ActivityIcon('bio', Icons.biotech_rounded, 'biologia medicina ricerca'),
    ActivityIcon('math', Icons.functions_rounded, 'formule matematica fisica'),
    ActivityIcon('quiz', Icons.quiz_rounded, 'esame quiz test domande'),
    ActivityIcon('pen', Icons.draw_rounded, 'penna scrivere disegnare'),
  ],
  'Lavoro': [
    ActivityIcon('briefcase', Icons.work_rounded, 'lavoro ufficio valigetta'),
    ActivityIcon('laptop', Icons.laptop_rounded, 'computer portatile pc'),
    ActivityIcon('desktop', Icons.computer_rounded, 'computer pc schermo'),
    ActivityIcon('code', Icons.code_rounded, 'programmazione codice sviluppo'),
    ActivityIcon('terminal', Icons.terminal_rounded, 'terminale programmazione server'),
    ActivityIcon('business', Icons.business_center_rounded, 'affari business cliente'),
    ActivityIcon('mail', Icons.mail_rounded, 'email posta messaggi'),
    ActivityIcon('call', Icons.call_rounded, 'telefono chiamata'),
    ActivityIcon('team', Icons.groups_rounded, 'riunione team gruppo persone'),
    ActivityIcon('meeting', Icons.meeting_room_rounded, 'riunione sala meeting'),
    ActivityIcon('analytics', Icons.analytics_rounded, 'analisi dati statistiche'),
    ActivityIcon('chart', Icons.bar_chart_rounded, 'grafico report numeri'),
    ActivityIcon('doc', Icons.description_rounded, 'documento file relazione'),
    ActivityIcon('folder', Icons.folder_rounded, 'cartella archivio pratiche'),
    ActivityIcon('print', Icons.print_rounded, 'stampa stampante'),
  ],
  'Sport': [
    ActivityIcon('barbell', Icons.fitness_center_rounded, 'palestra pesi allenamento'),
    ActivityIcon('run', Icons.directions_run_rounded, 'corsa correre jogging'),
    ActivityIcon('bike', Icons.directions_bike_rounded, 'bici ciclismo bicicletta'),
    ActivityIcon('swim', Icons.pool_rounded, 'nuoto piscina'),
    ActivityIcon('soccer', Icons.sports_soccer_rounded, 'calcio pallone'),
    ActivityIcon('basket', Icons.sports_basketball_rounded, 'basket pallacanestro'),
    ActivityIcon('tennis', Icons.sports_tennis_rounded, 'tennis padel racchetta'),
    ActivityIcon('yoga', Icons.self_improvement_rounded, 'yoga meditazione stretching'),
    ActivityIcon('hike', Icons.hiking_rounded, 'escursione montagna trekking'),
    ActivityIcon('martial', Icons.sports_martial_arts_rounded, 'arti marziali karate boxe'),
    ActivityIcon('volley', Icons.sports_volleyball_rounded, 'pallavolo volley'),
    ActivityIcon('skate', Icons.skateboarding_rounded, 'skate skateboard'),
    ActivityIcon('ski', Icons.downhill_skiing_rounded, 'sci neve'),
    ActivityIcon('rowing', Icons.rowing_rounded, 'canottaggio remo'),
    ActivityIcon('gym', Icons.sports_gymnastics_rounded, 'ginnastica esercizi'),
  ],
  'Casa': [
    ActivityIcon('house', Icons.home_rounded, 'casa'),
    ActivityIcon('broom', Icons.cleaning_services_rounded, 'pulizie pulire scopa'),
    ActivityIcon('laundry', Icons.local_laundry_service_rounded, 'bucato lavatrice'),
    ActivityIcon('kitchen', Icons.kitchen_rounded, 'cucina frigo'),
    ActivityIcon('bed', Icons.bed_rounded, 'letto dormire camera'),
    ActivityIcon('chair', Icons.chair_rounded, 'arredamento divano sedia'),
    ActivityIcon('yard', Icons.yard_rounded, 'giardino piante'),
    ActivityIcon('plant', Icons.grass_rounded, 'piante erba orto'),
    ActivityIcon('handyman', Icons.handyman_rounded, 'bricolage riparazioni attrezzi'),
    ActivityIcon('build', Icons.build_rounded, 'riparare manutenzione'),
    ActivityIcon('plumbing', Icons.plumbing_rounded, 'idraulica tubi'),
    ActivityIcon('cart', Icons.shopping_cart_rounded, 'spesa supermercato'),
    ActivityIcon('pets', Icons.pets_rounded, 'animali gatto cane'),
    ActivityIcon('water', Icons.water_drop_rounded, 'acqua annaffiare'),
    ActivityIcon('light', Icons.light_rounded, 'luce lampada'),
  ],
  'Creatività': [
    ActivityIcon('palette', Icons.palette_rounded, 'arte colori pittura'),
    ActivityIcon('brush', Icons.brush_rounded, 'pennello dipingere'),
    ActivityIcon('music', Icons.music_note_rounded, 'musica canzone'),
    ActivityIcon('piano', Icons.piano_rounded, 'pianoforte strumento'),
    ActivityIcon('mic', Icons.mic_rounded, 'canto podcast microfono'),
    ActivityIcon('headphones', Icons.headphones_rounded, 'ascoltare musica cuffie'),
    ActivityIcon('camera', Icons.photo_camera_rounded, 'foto fotografia'),
    ActivityIcon('video', Icons.videocam_rounded, 'video montaggio riprese'),
    ActivityIcon('movie', Icons.movie_rounded, 'film cinema'),
    ActivityIcon('theater', Icons.theater_comedy_rounded, 'teatro recitazione'),
    ActivityIcon('design', Icons.design_services_rounded, 'design grafica'),
    ActivityIcon('colors', Icons.color_lens_rounded, 'colori illustrazione'),
    ActivityIcon('magic', Icons.auto_fix_high_rounded, 'magia progetto creativo'),
    ActivityIcon('paint', Icons.format_paint_rounded, 'pittura vernice'),
    ActivityIcon('write', Icons.create_rounded, 'scrivere scrittura racconto'),
  ],
  'Salute': [
    ActivityIcon('heart', Icons.favorite_rounded, 'cuore amore salute'),
    ActivityIcon('spa', Icons.spa_rounded, 'relax benessere spa'),
    ActivityIcon('pill', Icons.medication_rounded, 'medicine farmaci'),
    ActivityIcon('hospital', Icons.local_hospital_rounded, 'ospedale medico visita'),
    ActivityIcon('pulse', Icons.monitor_heart_rounded, 'battito cardio salute'),
    ActivityIcon('sleep', Icons.bedtime_rounded, 'sonno dormire riposo'),
    ActivityIcon('mind', Icons.psychology_alt_rounded, 'terapia mente benessere'),
    ActivityIcon('drop', Icons.water_rounded, 'idratazione acqua'),
    ActivityIcon('air', Icons.air_rounded, 'respirazione aria'),
    ActivityIcon('healing', Icons.healing_rounded, 'cura guarire'),
    ActivityIcon('nature', Icons.emoji_nature_rounded, 'natura passeggiata'),
    ActivityIcon('smile', Icons.sentiment_satisfied_rounded, 'umore felice'),
    ActivityIcon('night', Icons.nightlight_rounded, 'notte luna'),
    ActivityIcon('pharmacy', Icons.local_pharmacy_rounded, 'farmacia'),
    ActivityIcon('meditate', Icons.self_improvement_rounded, 'meditazione respiro calma'),
  ],
  'Svago': [
    ActivityIcon('game', Icons.sports_esports_rounded, 'videogiochi gaming console'),
    ActivityIcon('gamepad', Icons.videogame_asset_rounded, 'giochi gamepad'),
    ActivityIcon('tv', Icons.tv_rounded, 'televisione serie tv'),
    ActivityIcon('series', Icons.movie_filter_rounded, 'serie film'),
    ActivityIcon('dice', Icons.casino_rounded, 'giochi da tavolo dadi'),
    ActivityIcon('puzzle', Icons.extension_rounded, 'puzzle rompicapo'),
    ActivityIcon('cafe', Icons.local_cafe_rounded, 'caffè bar pausa'),
    ActivityIcon('drink', Icons.local_bar_rounded, 'aperitivo drink'),
    ActivityIcon('party', Icons.celebration_rounded, 'festa amici'),
    ActivityIcon('park', Icons.park_rounded, 'parco natura'),
    ActivityIcon('beach', Icons.beach_access_rounded, 'mare spiaggia vacanza'),
    ActivityIcon('fun', Icons.attractions_rounded, 'divertimento luna park'),
    ActivityIcon('toys', Icons.toys_rounded, 'giocattoli'),
    ActivityIcon('robot', Icons.smart_toy_rounded, 'robot tecnologia'),
    ActivityIcon('reading', Icons.book_rounded, 'lettura svago libro'),
  ],
  'Viaggi': [
    ActivityIcon('flight', Icons.flight_rounded, 'aereo volo viaggio'),
    ActivityIcon('train', Icons.train_rounded, 'treno'),
    ActivityIcon('car', Icons.directions_car_rounded, 'auto macchina guida'),
    ActivityIcon('bus', Icons.directions_bus_rounded, 'autobus pullman'),
    ActivityIcon('luggage', Icons.luggage_rounded, 'valigia bagaglio'),
    ActivityIcon('map', Icons.map_rounded, 'mappa percorso'),
    ActivityIcon('explore', Icons.explore_rounded, 'esplorare bussola'),
    ActivityIcon('world', Icons.public_rounded, 'mondo'),
    ActivityIcon('hotel', Icons.hotel_rounded, 'hotel albergo'),
    ActivityIcon('landscape', Icons.landscape_rounded, 'paesaggio montagna'),
    ActivityIcon('walk', Icons.directions_walk_rounded, 'camminare passeggiata'),
    ActivityIcon('sail', Icons.sailing_rounded, 'barca vela'),
    ActivityIcon('moto', Icons.two_wheeler_rounded, 'moto scooter'),
    ActivityIcon('tram', Icons.tram_rounded, 'tram metro'),
    ActivityIcon('place', Icons.place_rounded, 'luogo posto'),
  ],
  'Cibo': [
    ActivityIcon('cook', Icons.restaurant_rounded, 'cucinare ristorante cibo'),
    ActivityIcon('pizza', Icons.local_pizza_rounded, 'pizza'),
    ActivityIcon('cake', Icons.cake_rounded, 'torta dolci compleanno'),
    ActivityIcon('coffee', Icons.coffee_rounded, 'caffè'),
    ActivityIcon('ramen', Icons.ramen_dining_rounded, 'ramen pasta'),
    ActivityIcon('bakery', Icons.bakery_dining_rounded, 'pane forno cornetto'),
    ActivityIcon('lunch', Icons.lunch_dining_rounded, 'pranzo panino'),
    ActivityIcon('icecream', Icons.icecream_rounded, 'gelato'),
    ActivityIcon('egg', Icons.egg_rounded, 'colazione uova'),
    ActivityIcon('meal', Icons.set_meal_rounded, 'pasto pesce'),
    ActivityIcon('wine', Icons.liquor_rounded, 'vino'),
    ActivityIcon('dining', Icons.local_dining_rounded, 'cena'),
    ActivityIcon('kebab', Icons.kebab_dining_rounded, 'grigliata'),
    ActivityIcon('rice', Icons.rice_bowl_rounded, 'riso ciotola'),
    ActivityIcon('cookie', Icons.cookie_rounded, 'biscotto'),
  ],
  'Altro': [
    ActivityIcon('circle', Icons.circle_rounded, 'cerchio generico'),
    ActivityIcon('star', Icons.star_rounded, 'stella preferito'),
    ActivityIcon('bolt', Icons.bolt_rounded, 'energia veloce'),
    ActivityIcon('eco', Icons.eco_rounded, 'ecologia foglia'),
    ActivityIcon('savings', Icons.savings_rounded, 'risparmi soldi'),
    ActivityIcon('payments', Icons.payments_rounded, 'pagamenti bollette'),
    ActivityIcon('schedule', Icons.schedule_rounded, 'orario tempo'),
    ActivityIcon('event', Icons.event_rounded, 'evento calendario'),
    ActivityIcon('language', Icons.language_rounded, 'web internet'),
    ActivityIcon('chat', Icons.forum_rounded, 'chat conversazione'),
    ActivityIcon('volunteer', Icons.volunteer_activism_rounded, 'volontariato aiuto'),
    ActivityIcon('baby', Icons.child_care_rounded, 'bambini figli'),
    ActivityIcon('church', Icons.church_rounded, 'chiesa'),
    ActivityIcon('flag', Icons.flag_rounded, 'obiettivo bandiera'),
    ActivityIcon('rocket', Icons.rocket_launch_rounded, 'progetto lancio'),
  ],
};

final Map<String, ActivityIcon> _byKey = {
  for (final g in kIconGroups.values)
    for (final i in g) i.key: i,
};

IconData iconFor(String key) => _byKey[key]?.icon ?? Icons.circle_rounded;

/// Icons whose key or Italian keywords contain [query].
List<ActivityIcon> searchIcons(String query) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return const [];
  return [
    for (final i in _byKey.values)
      if (i.words.contains(q) || i.key.contains(q)) i,
  ];
}
