import 'dart:typed_data';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:timezone/data/latest_all.dart' as tzdata;
import 'package:timezone/timezone.dart' as tz;

import 'settings.dart';

/// Scheduled reminders. The live timer notification is native (see live.dart);
/// here are the break/pause/pomodoro reminder (one at a time) and to-do ones.
const int kReminderId = 2;

/// "Torna al lavoro" has its own id: when an auto-pause or pomodoro deadline
/// falls due, the pause starts at once and schedules its end, which must not
/// replace the alarm that is ringing for the deadline.
const int kPauseEndId = 4;
const int kTestReminderId = 5;
const int kTodoIdBase = 100000;

/// Bundled sounds in android/app/src/main/res/raw, generated by
/// tool/make_sounds.py.
const Map<String, String> kBundledSounds = {
  'campanella': 'Campanella',
  'marimba': 'Marimba',
  'gong': 'Gong morbido',
  'duenote': 'Due note',
  'carillon': 'Carillon',
};

final plugin = FlutterLocalNotificationsPlugin();
bool _tzReady = false;

Future<void> initTz() async {
  if (_tzReady) return;
  tzdata.initializeTimeZones();
  final local = await FlutterTimezone.getLocalTimezone();
  tz.setLocalLocation(tz.getLocation(local.identifier));
  _tzReady = true;
}

Future<void> initNotifications({
  DidReceiveNotificationResponseCallback? onTap,
  DidReceiveBackgroundNotificationResponseCallback? onBackgroundTap,
  bool requestPermission = true,
}) async {
  await initTz();
  await plugin.initialize(
    settings: const InitializationSettings(
      android: AndroidInitializationSettings('@drawable/ic_taime_notif'),
    ),
    onDidReceiveNotificationResponse: onTap,
    onDidReceiveBackgroundNotificationResponse: onBackgroundTap,
  );
  if (requestPermission) {
    await _android?.requestNotificationsPermission();
  }
}

AndroidFlutterLocalNotificationsPlugin? get _android => plugin
    .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();

/// Channel sounds cannot change after creation, so every sound setup gets its
/// own channel id; the previous one is deleted when it changes.
String reminderChannelId(Settings s) {
  final key = '${s.soundKind}|${s.soundValue}|${s.soundLoop}|${s.soundVibrate}';
  // FNV-1a: the same id on every run and every isolate (String.hashCode is
  // not guaranteed to be).
  var h = 0x811c9dc5;
  for (final c in key.codeUnits) {
    h = ((h ^ c) * 0x01000193) & 0xFFFFFFFF;
  }
  return 'rem_${h.toRadixString(16)}';
}

/// Removes reminder channels left over by older sound settings.
Future<void> dropStaleReminderChannels(Settings s) async {
  try {
    final keep = reminderChannelId(s);
    for (final c in await _android?.getNotificationChannels() ?? const <AndroidNotificationChannel>[]) {
      if (c.id.startsWith('rem_') && c.id != keep) {
        await _android?.deleteNotificationChannel(channelId: c.id);
      }
    }
  } catch (_) {}
}

String? _lastChannel;

AndroidNotificationSound? _sound(Settings s) => switch (s.soundKind) {
  'bundled' => RawResourceAndroidNotificationSound(s.soundValue),
  _ => s.soundValue.isEmpty ? null : UriAndroidNotificationSound(s.soundValue),
};

/// Plays like an alarm: alarm stream, heard through Do Not Disturb (when
/// alarms are allowed there, the Android default), optionally insistent.
AndroidNotificationDetails _reminderDetails(
  Settings s,
  List<AndroidNotificationAction> actions,
) {
  final id = reminderChannelId(s);
  return AndroidNotificationDetails(
    id,
    'Promemoria (${s.soundName})',
    channelDescription: 'Pause, fine pausa e pomodoro. Suona come una sveglia.',
    importance: Importance.max,
    priority: Priority.max,
    category: AndroidNotificationCategory.alarm,
    audioAttributesUsage: AudioAttributesUsage.alarm,
    sound: _sound(s),
    playSound: true,
    enableVibration: s.soundVibrate,
    vibrationPattern: s.soundVibrate
        ? Int64List.fromList([0, 400, 200, 400])
        : null,
    additionalFlags: s.soundLoop ? Int32List.fromList([4]) : null, // FLAG_INSISTENT
    timeoutAfter: s.soundLoop ? 60000 : null,
    visibility: NotificationVisibility.public,
    // Wakes the screen and shows on the lock screen, like an alarm clock.
    fullScreenIntent: true,
    actions: actions,
  );
}

/// Android 14+ may ask the user to allow full-screen alerts; returns at once
/// when they are already allowed (the usual case for an installed APK).
Future<void> requestFullScreenAlerts() async {
  try {
    await _android?.requestFullScreenIntentPermission();
  } catch (_) {}
}

Future<void> _dropOldChannel(Settings s) async {
  final id = reminderChannelId(s);
  if (_lastChannel != null && _lastChannel != id) {
    await _android?.deleteNotificationChannel(channelId: _lastChannel!);
  }
  _lastChannel = id;
}

Future<void> scheduleReminder({
  required Settings settings,
  required DateTime at,
  required String title,
  required String body,
  required List<AndroidNotificationAction> actions,
  int id = kReminderId,
}) async {
  await initTz();
  await plugin.cancel(id: id);
  if (!at.isAfter(DateTime.now())) return;
  await _dropOldChannel(settings);
  await _scheduleAlarm(
    id: id,
    at: at,
    title: title,
    body: body,
    details: NotificationDetails(android: _reminderDetails(settings, actions)),
  );
}

/// Schedules like an alarm clock; if the phone refuses exact alarms, falls
/// back to an exact-while-idle one and then to an inexact one, so a reminder
/// always arrives (at worst a little late).
Future<void> _scheduleAlarm({
  required int id,
  required DateTime at,
  required String title,
  required String body,
  required NotificationDetails details,
  String? payload,
}) async {
  Object? error;
  for (final mode in const [
    AndroidScheduleMode.alarmClock,
    AndroidScheduleMode.exactAllowWhileIdle,
    AndroidScheduleMode.inexactAllowWhileIdle,
  ]) {
    try {
      await plugin.zonedSchedule(
        id: id,
        scheduledDate: tz.TZDateTime.from(at, tz.local),
        title: title,
        body: body,
        payload: payload,
        androidScheduleMode: mode,
        notificationDetails: details,
      );
      return;
    } catch (e) {
      error = e;
    }
  }
  throw error!;
}

/// Notification check: the same reminder as a real pause, in [seconds].
/// Lock the phone to see it light up the screen.
Future<void> testPauseReminder(Settings settings, {int seconds = 10}) async {
  await initTz();
  await _dropOldChannel(settings);
  await _scheduleAlarm(
    id: kTestReminderId,
    at: DateTime.now().add(Duration(seconds: seconds)),
    title: 'Prova della pausa',
    body: 'Se lo schermo si è acceso e hai sentito il suono, i promemoria funzionano.',
    details: NotificationDetails(android: _reminderDetails(settings, const [])),
  );
}

/// Cancels ignore failures: a reminder that cannot be withdrawn must never
/// stop the data change that asked for it.
Future<void> _cancel(int id) async {
  try {
    await plugin.cancel(id: id);
  } catch (_) {}
}

Future<void> cancelReminder() => _cancel(kReminderId);

Future<void> cancelPauseEndReminder() => _cancel(kPauseEndId);

/// Call with the *old* settings before changing the sound.
Future<void> deleteReminderChannel(Settings old) async =>
    _android?.deleteNotificationChannel(channelId: reminderChannelId(old));

/// "Prova suono": fires the reminder right now with the current settings.
Future<void> testReminderSound(Settings settings) async {
  await _dropOldChannel(settings);
  await plugin.show(
    id: kTestReminderId,
    title: 'Prova suono',
    body: settings.soundName,
    notificationDetails: NotificationDetails(
      android: _reminderDetails(settings, const []),
    ),
  );
}

/// Asks Android for permission to notify (Android 13+); true when allowed.
Future<bool> askNotificationPermission() async => await _android?.requestNotificationsPermission() ?? true;

/// Notification check: a to-do reminder, right now.
Future<void> testTodoNotification() => plugin.show(
  id: kTodoIdBase,
  title: 'Prova di un to-do',
  body: 'I promemoria dei to-do e delle note arrivano così.',
  notificationDetails: const NotificationDetails(android: _todoDetails),
);

AndroidNotificationAction action(String id, String title) =>
    AndroidNotificationAction(id, title, showsUserInterface: false);

// --- To-do reminders ----------------------------------------------------------

const _todoDetails = AndroidNotificationDetails(
  'todo',
  'Promemoria to-do',
  channelDescription: 'Scadenze della lista to-do',
  importance: Importance.high,
  priority: Priority.high,
  category: AndroidNotificationCategory.reminder,
);

Future<void> scheduleTodoReminder({
  required int todoId,
  required DateTime at,
  required String title,
  required String body,
}) async {
  await initTz();
  await plugin.cancel(id: kTodoIdBase + todoId);
  if (!at.isAfter(DateTime.now())) return;
  await _scheduleAlarm(
    id: kTodoIdBase + todoId,
    at: at,
    title: title,
    body: body,
    payload: 'todo:$todoId',
    details: const NotificationDetails(android: _todoDetails),
  );
}

Future<void> cancelTodoReminder(int todoId) => _cancel(kTodoIdBase + todoId);

// --- Note reminders -----------------------------------------------------------

const int kNoteIdBase = 200000;

const _noteDetails = AndroidNotificationDetails(
  'note',
  'Promemoria note',
  channelDescription: 'Le note con un promemoria',
  importance: Importance.high,
  priority: Priority.high,
  category: AndroidNotificationCategory.reminder,
);

Future<void> scheduleNoteReminder({required int noteId, required DateTime at, required String text}) async {
  await initTz();
  await plugin.cancel(id: kNoteIdBase + noteId);
  if (!at.isAfter(DateTime.now())) return;
  final lines = text.trim().split('\n');
  await _scheduleAlarm(
    id: kNoteIdBase + noteId,
    at: at,
    title: lines.first.length > 60 ? '${lines.first.substring(0, 60)}…' : lines.first,
    body: lines.length > 1 ? lines.skip(1).join(' ').trim() : 'Nota di Taime',
    payload: 'note:$noteId',
    details: const NotificationDetails(android: _noteDetails),
  );
}

Future<void> cancelNoteReminder(int noteId) => _cancel(kNoteIdBase + noteId);

// --- "Still there?" -----------------------------------------------------------

const int kAwayId = 3;

const _awayDetails = AndroidNotificationDetails(
  'away',
  'Timer dimenticato',
  channelDescription: 'Avvisa se l\'app resta in background con un timer attivo',
  importance: Importance.high,
  priority: Priority.high,
  category: AndroidNotificationCategory.reminder,
);

/// With the app in the background and a timer running, nudge after a while.
/// Uses the phone's default notification sound.
Future<void> scheduleAwayReminder({required DateTime at, required String activity}) async {
  try {
    await initTz();
    await _scheduleAlarm(
      id: kAwayId,
      at: at,
      title: 'Il timer è ancora attivo',
      body: '$activity sta ancora contando. Stai ancora lavorando?',
      details: NotificationDetails(
        android: AndroidNotificationDetails(
          _awayDetails.channelId,
          _awayDetails.channelName,
          channelDescription: _awayDetails.channelDescription,
          importance: Importance.high,
          priority: Priority.high,
          category: AndroidNotificationCategory.reminder,
          actions: [action('pause', 'Pausa'), action('stop', 'Termina')],
        ),
      ),
    );
  } catch (_) {}
}

Future<void> cancelAwayReminder() => _cancel(kAwayId);
