import 'dart:typed_data';

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:timezone/data/latest_all.dart' as tzdata;
import 'package:timezone/timezone.dart' as tz;

import 'settings.dart';

/// Scheduled reminders. The live timer notification is native (see live.dart);
/// here are the break/pause/pomodoro reminder (one at a time) and to-do ones.
const int kReminderId = 2;
const int kTodoIdBase = 100000;

/// Bundled sounds in android/app/src/main/res/raw, generated by
/// tool/make_sounds.py.
const Map<String, String> kBundledSounds = {
  'campanella': 'Campanella',
  'marimba': 'Marimba',
  'gong': 'Gong morbido',
  'duenote': 'Due note',
  'carillon': 'Carillon',
};

final plugin = FlutterLocalNotificationsPlugin();
bool _tzReady = false;

Future<void> initTz() async {
  if (_tzReady) return;
  tzdata.initializeTimeZones();
  final local = await FlutterTimezone.getLocalTimezone();
  tz.setLocalLocation(tz.getLocation(local.identifier));
  _tzReady = true;
}

Future<void> initNotifications({
  DidReceiveNotificationResponseCallback? onTap,
  DidReceiveBackgroundNotificationResponseCallback? onBackgroundTap,
  bool requestPermission = true,
}) async {
  await initTz();
  await plugin.initialize(
    settings: const InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
    ),
    onDidReceiveNotificationResponse: onTap,
    onDidReceiveBackgroundNotificationResponse: onBackgroundTap,
  );
  if (requestPermission) {
    await _android?.requestNotificationsPermission();
  }
}

AndroidFlutterLocalNotificationsPlugin? get _android => plugin
    .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();

/// Channel sounds cannot change after creation, so every sound setup gets its
/// own channel id; the previous one is deleted when it changes.
String reminderChannelId(Settings s) {
  final key = '${s.soundKind}|${s.soundValue}|${s.soundLoop}|${s.soundVibrate}';
  return 'rem_${key.hashCode.toUnsigned(32).toRadixString(16)}';
}

String? _lastChannel;

AndroidNotificationSound? _sound(Settings s) => switch (s.soundKind) {
  'bundled' => RawResourceAndroidNotificationSound(s.soundValue),
  _ => s.soundValue.isEmpty ? null : UriAndroidNotificationSound(s.soundValue),
};

/// Plays like an alarm: alarm stream, heard through Do Not Disturb (when
/// alarms are allowed there, the Android default), optionally insistent.
AndroidNotificationDetails _reminderDetails(
  Settings s,
  List<AndroidNotificationAction> actions,
) {
  final id = reminderChannelId(s);
  return AndroidNotificationDetails(
    id,
    'Promemoria (${s.soundName})',
    channelDescription: 'Pause, fine pausa e pomodoro. Suona come una sveglia.',
    importance: Importance.max,
    priority: Priority.max,
    category: AndroidNotificationCategory.alarm,
    audioAttributesUsage: AudioAttributesUsage.alarm,
    sound: _sound(s),
    playSound: true,
    enableVibration: s.soundVibrate,
    vibrationPattern: s.soundVibrate
        ? Int64List.fromList([0, 400, 200, 400])
        : null,
    additionalFlags: s.soundLoop ? Int32List.fromList([4]) : null, // FLAG_INSISTENT
    timeoutAfter: s.soundLoop ? 60000 : null,
    visibility: NotificationVisibility.public,
    // Wakes the screen and shows on the lock screen, like an alarm clock.
    fullScreenIntent: true,
    actions: actions,
  );
}

/// Android 14+ may ask the user to allow full-screen alerts; returns at once
/// when they are already allowed (the usual case for an installed APK).
Future<void> requestFullScreenAlerts() async {
  try {
    await _android?.requestFullScreenIntentPermission();
  } catch (_) {}
}

Future<void> _dropOldChannel(Settings s) async {
  final id = reminderChannelId(s);
  if (_lastChannel != null && _lastChannel != id) {
    await _android?.deleteNotificationChannel(channelId: _lastChannel!);
  }
  _lastChannel = id;
}

Future<void> scheduleReminder({
  required Settings settings,
  required DateTime at,
  required String title,
  required String body,
  required List<AndroidNotificationAction> actions,
}) async {
  await initTz();
  await plugin.cancel(id: kReminderId);
  if (!at.isAfter(DateTime.now())) return;
  await _dropOldChannel(settings);
  await plugin.zonedSchedule(
    id: kReminderId,
    scheduledDate: tz.TZDateTime.from(at, tz.local),
    title: title,
    body: body,
    androidScheduleMode: AndroidScheduleMode.alarmClock,
    notificationDetails: NotificationDetails(
      android: _reminderDetails(settings, actions),
    ),
  );
}

Future<void> cancelReminder() => plugin.cancel(id: kReminderId);

/// Call with the *old* settings before changing the sound.
Future<void> deleteReminderChannel(Settings old) async =>
    _android?.deleteNotificationChannel(channelId: reminderChannelId(old));

/// "Prova suono": fires the reminder right now with the current settings.
Future<void> testReminderSound(Settings settings) async {
  await _dropOldChannel(settings);
  await plugin.show(
    id: kReminderId + 1,
    title: 'Prova suono',
    body: settings.soundName,
    notificationDetails: NotificationDetails(
      android: _reminderDetails(settings, const []),
    ),
  );
}

AndroidNotificationAction action(String id, String title) =>
    AndroidNotificationAction(id, title, showsUserInterface: false);

// --- To-do reminders ----------------------------------------------------------

const _todoDetails = AndroidNotificationDetails(
  'todo',
  'Promemoria to-do',
  channelDescription: 'Scadenze della lista to-do',
  importance: Importance.high,
  priority: Priority.high,
  category: AndroidNotificationCategory.reminder,
);

Future<void> scheduleTodoReminder({
  required int todoId,
  required DateTime at,
  required String title,
  required String body,
}) async {
  await initTz();
  await plugin.cancel(id: kTodoIdBase + todoId);
  if (!at.isAfter(DateTime.now())) return;
  await plugin.zonedSchedule(
    id: kTodoIdBase + todoId,
    scheduledDate: tz.TZDateTime.from(at, tz.local),
    title: title,
    body: body,
    payload: 'todo:$todoId',
    androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
    notificationDetails: const NotificationDetails(android: _todoDetails),
  );
}

Future<void> cancelTodoReminder(int todoId) =>
    plugin.cancel(id: kTodoIdBase + todoId);

// --- Note reminders -----------------------------------------------------------

const int kNoteIdBase = 200000;

const _noteDetails = AndroidNotificationDetails(
  'note',
  'Promemoria note',
  channelDescription: 'Le note con un promemoria',
  importance: Importance.high,
  priority: Priority.high,
  category: AndroidNotificationCategory.reminder,
);

Future<void> scheduleNoteReminder({required int noteId, required DateTime at, required String text}) async {
  await initTz();
  await plugin.cancel(id: kNoteIdBase + noteId);
  if (!at.isAfter(DateTime.now())) return;
  final lines = text.trim().split('\n');
  await plugin.zonedSchedule(
    id: kNoteIdBase + noteId,
    scheduledDate: tz.TZDateTime.from(at, tz.local),
    title: lines.first.length > 60 ? '${lines.first.substring(0, 60)}…' : lines.first,
    body: lines.length > 1 ? lines.skip(1).join(' ').trim() : 'Nota di Taime',
    payload: 'note:$noteId',
    androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
    notificationDetails: const NotificationDetails(android: _noteDetails),
  );
}

Future<void> cancelNoteReminder(int noteId) => plugin.cancel(id: kNoteIdBase + noteId);

// --- "Still there?" -----------------------------------------------------------

const int kAwayId = 3;

const _awayDetails = AndroidNotificationDetails(
  'away',
  'Timer dimenticato',
  channelDescription: 'Avvisa se l\'app resta in background con un timer attivo',
  importance: Importance.high,
  priority: Priority.high,
  category: AndroidNotificationCategory.reminder,
);

/// With the app in the background and a timer running, nudge after a while.
/// Uses the phone's default notification sound.
Future<void> scheduleAwayReminder({required DateTime at, required String activity}) async {
  try {
    await initTz();
    await plugin.zonedSchedule(
      id: kAwayId,
      scheduledDate: tz.TZDateTime.from(at, tz.local),
      title: 'Il timer è ancora attivo',
      body: '$activity sta ancora contando. Stai ancora lavorando?',
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      notificationDetails: NotificationDetails(
        android: AndroidNotificationDetails(
          _awayDetails.channelId,
          _awayDetails.channelName,
          channelDescription: _awayDetails.channelDescription,
          importance: Importance.high,
          priority: Priority.high,
          category: AndroidNotificationCategory.reminder,
          actions: [action('pause', 'Pausa'), action('stop', 'Termina')],
        ),
      ),
    );
  } catch (_) {}
}

Future<void> cancelAwayReminder() async {
  try {
    await plugin.cancel(id: kAwayId);
  } catch (_) {}
}
